/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.theora.codec;

enum {
    TH_EFAULT = -1,
    TH_EINVAL = -10,
    TH_EBADHEADER = -20,
    TH_ENOTFORMAT = -21,
    TH_EVERSION = -22,
    TH_EIMPL = -23,
    TH_EBADPACKET = -24,
    TH_DUPFRAME = 1,
}

alias int th_colorspace;
enum {
    TH_CS_UNSPECIFIED,
    TH_CS_ITU_REC_470M,
    TH_CS_ITU_REC_470BG,
    TH_CS_NSPACES,
}

alias int th_pixel_fmt;
enum {
    TH_PF_420,
    TH_PF_RSVD,
    TH_PF_422,
    TH_PF_444,
    TH_PF_NFORMATS,
}

struct th_img_plane {
    int width;
    int height;
    int stride;
    ubyte* data;
}

alias th_ycbcr_buffer = th_img_plane[ 3 ];

struct th_info {
    ubyte version_major;
    ubyte version_minor;
    ubyte version_subminor;
    uint frame_width;
    uint frame_height;
    uint pic_width;
    uint pic_height;
    uint pic_x;
    uint pic_y;
    uint fps_numerator;
    uint fps_denominator;
    uint aspect_numerator;
    uint aspect_denominator;
    th_colorspace colorspace;
    th_pixel_fmt pixel_fmt;
    int target_bitrate;
    int quality;
    int keyframe_granule_shift;
}

struct th_comment {
    char** user_comments;
    int* comment_lengths;
    int comments;
    char* vendor;
}

alias th_quant_base = ubyte[ 64 ];

struct th_quant_ranges {
    int nranges;
    const( int )* sizes;
    const( th_quant_base )* base_matrices;
}

struct th_quant_info {
    ushort[ 64 ] dc_scale;
    ushort[ 64 ] ac_scale;
    ubyte[ 64 ] loop_filter_limits;
    th_quant_ranges[ 2 ][ 3 ] qi_ranges;
}

enum {
    TH_NHUFFMAN_TABLES = 80,
    TH_NDCT_TOKENS = 32,
}

struct th_huff_code {
    uint pattern;
    int nbits;
}